config/routes.rb
Karibuni::Application.routes.draw do

  root :to => 'pages#index'

  #рассылка
  get '/user_start' => 'user#start'
  get '/user_unsubscribe/:id' => 'user#unsubscribe', :as => :unsubscribe
  #рассылка


  #начало роуты для корзины и заказов
  post 'order_add_product' => 'order#order_add_product'
  delete '/products_order_destroy/:id/:product_id' => 'order#products_order_destroy', :as => :products_order_destroy
  #get '/ajax/mini_cart' => 'ajax#mini_cart'
  get 'cart' => 'order#cart', :as => :cart
  get '/order/confirm/:id' => 'order#confirm', :as => :order_confirm
  put 'order/create/:id' => 'order#create'
  get 'order/:id' => 'order#show'
  #конец роуты для корзины и заказов


  resources :feedbacks, :only => [:index, :create]

  #begin ajax
  #get '/ajax/product/:id' => 'ajax#product'
  #end ajax


  get '/admin' => 'admin/dashboard#index'


  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  namespace :admin do
    resources :pages do
      collection do

        post :rebuild

        get ':id/edit' => 'pages#edit'
        get '*section/:id/edit' => 'pages#edit'

        get ':id' => 'pages#show'
        get '*section/:id' => 'pages#show'

        get ':id' => 'pages#new'

        put '*section/:id' => 'pages#update'
        put ':id' => 'pages#update'

        delete ':id' => 'pages#destroy'
        delete '*section/:id' => 'pages#destroy'

      end
    end
  end

  #begin хаки для страниц из-за ёбнутейшего роутинга ниже
  #get '/:id' => 'pages#show'
  #end хаки для страниц из-за ёбнутейшего роутинга ниже


  resources :categories, :only => [], :path => '/shop' do
    get 'product/:id' => 'products#show', :as => :product
  end
  resources :categories, :only => [], :path => '/shop/*section' do
    get 'product/:id' => 'products#show', :as => :product
  end


  get '/shop/' => 'categories#index', :as => :shop
  get '/shop/sales' => 'categories#sales', :as => :shop_sales
  get '/shop/:cat_id/product' => 'categories#category', :as => :category
  get '/shop/*section/:cat_id/product' => 'categories#category', :as => :category
  

  resources :pages, :path => "/", :only => [:index, :show]

end

app/models/order.rb
# encoding: utf-8
class Order < ActiveRecord::Base

  attr_accessible :username, :surname, :email, :phone, :address, :comment, :data,
                  :price, :payment, :order_confirm, :confirm

  attr_reader :items
  #
  validates_length_of :username, :in => 2..50, :message => "Имя должно быть длинной не менее 2 и не более 50 символов"
  validates :email, :format => {:with => /[A-Za-z0-9._%+-]+@([A-Za-z0-9-]+\.)+([A-Za-z0-9]{2,4}|museum)/,
                                :message => "Не правильно указан адрес e-mail"}
  validates_length_of :phone, :in => 5..15, :message => "Не указан телефон"
  validates_length_of :address, :in => 5..300, :message => "Не указан адрес"

  #begin объявлеям связь с упражнениями многие ко многим, через соединительную модель motions_programs
  has_many :products_orders
  has_many :products, :through => :products_orders
  #end объявлеям связь с упражнениями многие ко многим, через соединительную модель motions_programs


  def set_price(order_price, product_price)
      self.price = order_price.to_i + product_price
  end

  def re_price(order_price, product_price)
      self.price = 989
  end


end

app/controllers/order_controller.rb
class OrderController < ApplicationController


  def order_add_product

    if session[:order_id]
      @order = Order.find(session[:order_id])
      @order_id = @order.id
    else
      @order = Order.new
      @order.save(:validate => false)
      @order_id = @order.id
      session[:order_id] = @order_id
    end


    @products_order = ProductsOrder.where("product_id = ? AND order_id = ?", params[:id], @order_id).first

    #общая стоимость заказа
    @product = Product.find(params[:id])

    #обновим счётчик для данного продукта
    @product.update_attribute(:hit, @product.hit.to_i + 1)

    if @product.sale.to_i > 0
      @order.set_price(@order.price, @product.price_sale)
    else
      @order.set_price(@order.price, @product.price)
    end

    @order.update_attribute(:confirm, "В процессе")

    if @products_order
      @products_order.update_attributes(:order_id => @order_id, :product_id => params[:id], :size => params[:size], :sum => @products_order.sum + 1)
    else
      @products_order = ProductsOrder.new(:order_id => @order_id, :product_id => params[:id], :size => params[:size], :sum => 1)
      @products_order.save
    end


    @quantity = 0
    for product in @order.products
      @products_orders = ProductsOrder.where("product_id = ? AND order_id = ?", product.id, @order_id).first
      @count = @products_orders.sum
      @quantity = @quantity + @count
    end

    respond_to do |format|
      format.html { redirect_to cart_path(@order) }
      #format.js {}
      format.json { render :json => @order, :status => :created, :location => @order }
    end

  end


  def order_product_count

  end


  def products_order_destroy
    @order = Order.find(params[:id])
    @product = Product.find(params[:product_id])

    #общая стоимость заказа
    @products_order = ProductsOrder.where("product_id = ? AND order_id = ?", params[:product_id], params[:id]).first

    if @product.sale.to_i > 0
      # @order.re_price(@order.price, @product.price_sale.to_i * @products_order.sum)
      @count = @order.price.to_i - @product.price_sale.to_i * @products_order.sum
    else
      # @order.re_price(@order.price, @product.price.to_i * @products_order.sum)
      @count = @order.price.to_i - @product.price.to_i * @products_order.sum
    end
    
    # unless @product.sale
    #   @count = @order.price.to_i - @product.price.to_i * @products_order.sum
    # end
    # if @product.sale
    #   @count = @order.price.to_i - @product.price_sale.to_i * @products_order.sum
    # end
    # 
    @order.update_attribute(:price, @count)

    @order.products.delete(@product)

    respond_to do |format|
      format.html { redirect_to cart_url(@order) }
      format.json { head :no_content }
    end
  end


  def cart
    if session[:order_id]
      @order = Order.find(session[:order_id])
    else
      @order = Order.new
      @order.save(:validate => false)
      session[:order_id] = @order.id
    end
    @order_id = @order.id
    @products = @order.products

    @price = @order.price

    @meta_title = "Корзина"
  end

  def confirm
    @order = Order.find(params[:id])

    @order_id = params[:id]
    @products = @order.products
    @price = @order.price
  end


  def create
    @order = Order.find(params[:id])
    if @order.update_attributes(params[:order])
      session[:order_id] = nil
      redirect_to :action => :show, :id => @order.id
      OrderMailer.order_cofirm(@order).deliver
      OrderMailer.order_cofirm_user(@order).deliver
    else
      render :action => :confirm
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_id = @order.id
    @products = @order.products
    @price = @order.price
  end

end

app/views/admin/orders/_form.haml
= semantic_form_for [:admin, @order] do |f|
  = f.inputs "Новая страница" do
    = f.input :username, :label => "Имя"
    = f.input :surname, :label => "Фамилия"
    = f.input :phone, :label => "Контактный телефон"
    = f.input :email, :label => "Email"
    = f.input :address, :label => "Адрес для доставки"
    = f.input :date, :label => "Желаемая дата доставки"
    = f.input :first_time, :label => "Желаемое время доставки с"
    = f.input :last_time, :label => "до"
    = f.input :price, :label => "Стоимость (руб.)"
    = f.input :payment, :label => "Форма оплаты", :as => :select, :collection => [['Наличными курьеру', 'Наличными курьеру'], ['Пластиковой картой', 'Пластиковой картой'], ['Безналичный расчёт', 'Безналичный расчёт']]
    = f.input :confirm, :label => "Стастус зака", :as => :select, :collection => [['В обработке','В обработке'], ['Готово','Готово'], ['Отказ','Отказ'], ['Новый','Новый']]

  .panel{:style => "margin-top:30px"}
    %h3 Содержимое заказа
    .panel_contents

      .attributes_table
        %table
          %tr.row
            %th Комментарий к заказу
            %td= @order.comment
      .attributes_table
        %table{:style=>"width:auto"}
          %tr
            %td Наименование
            %td Изображение
            %td Порция
            %td Количество
            %td Цена
            %td Итого
          -for cart_item in JSON.parse(@order.data)
            %tr
              -if cart_item
                -product = Product.find(cart_item[0])
                %td= link_to product.title, [product.category, product], :target => '_blank'
                -if product.attachments.find_last
                  %td= image_tag product.attachments.find_last.file_url(:mini)
                %td
                  = product.weight.to_i
                  гр.
                %td= cart_item[1]
                %td= product.price.to_i
                %td= product.price.to_i * cart_item[1]

  = f.actions do
    = f.action :submit

app/views/admin/orders/_index.haml
%table#index_table_orders.index_table.index{:cellspacing => "0", :cellpadding => "0", :border => "0",  :paginator => "true"}
  %thead
    %tr
      %th №
      %th Клиент
      %th Телефон
      %th Email
      %th Стоимость(руб.)
      %th Дата
      %th Статус заказа
      %th

  %tbody
    -@orders.each do |item|
      %tr{:class => "#{'new' if item.confirm == 'Новый' } #{'process' if item.confirm == 'В обработке' } #{'done' if item.confirm == 'Готово' } #{'fail' if item.confirm == 'Отказ' }"}
        %td=link_to item.id, admin_order_path(item)
        %td
          = item.username
          = item.surname
        %td= item.phone
        %td= item.email
        %td= item.price.to_i
        %td= raw I18n.l item.created_at, :format => :day
        %td= item.confirm
        %td
          =link_to "Редактировать", edit_admin_order_path(item)
          &nbsp;
          =link_to "Удалить", admin_order_path(item), :confirm => 'Точно удалить?', :method => :delete

app/views/admin/orders/_show.haml
.panel
  %h3
    Заказ №
    = @order.id
    %b{:style=>"color:green"} (#{@order.confirm})

  .panel_contents
    .attributes_table
      %table
        %tr.row
          %th ФИО
          %td
            = @order.username
            = @order.surname
        %tr.row
          %th Контактный телефон
          %td= @order.phone
        %tr.row
          %th Email
          %td= @order.email
        %tr.row
          %th Адрес для доставки
          %td= @order.address

        %tr.row
          %th Комментарий к заказу
          %td= @order.comment
        %tr.row
          %th Стоимость (руб.)
          %td= @order.price.to_i

.panel{:style => "margin-top:30px"}
  %h3 Содержимое заказа
  .panel_contents
    .attributes_table
      -if @order.products.length != 0
        %table{:style=>"width:auto"}
          %tr
            %th Изображение
            %th Название
            %th Описание
            %th кол-во
            %th Цена
          -for item in @order.products
            -@products_order = ProductsOrder.where("product_id = ? AND order_id = ?", item.id, @order.id).first
            -@count = @products_order.sum
            -@size = @products_order.size

            %tr
              %td
                -if item.attachments.find_last
                  = image_tag item.attachments.find_last.file_url(:mini)
                -else
                  %img{:src => '/images/nophoto_small.png'}
              %td
                %div= link_to item.title, [item.category, item]
                .size
                  Размер:
                  %b=@size

              %td= item.desc
              %td=@count
              %td
                = item.price.to_i * @count
                руб.