config/routes.rb
Karibuni::Application.routes.draw do

  root :to => 'pages#index'

  #рассылка
  get '/user_start' => 'user#start'
  get '/user_unsubscribe/:id' => 'user#unsubscribe', :as => :unsubscribe
  #рассылка


  #начало роуты для корзины и заказов
  post 'order_add_product' => 'order#order_add_product'
  delete '/products_order_destroy/:id/:product_id' => 'order#products_order_destroy', :as => :products_order_destroy
  #get '/ajax/mini_cart' => 'ajax#mini_cart'
  get 'cart' => 'order#cart', :as => :cart
  get '/order/confirm/:id' => 'order#confirm', :as => :order_confirm
  put 'order/create/:id' => 'order#create'
  get 'order/:id' => 'order#show'
  #конец роуты для корзины и заказов


  resources :feedbacks, :only => [:index, :create]

  #begin ajax
  #get '/ajax/product/:id' => 'ajax#product'
  #end ajax


  get '/admin' => 'admin/dashboard#index'


  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  namespace :admin do
    resources :pages do
      collection do

        post :rebuild

        get ':id/edit' => 'pages#edit'
        get '*section/:id/edit' => 'pages#edit'

        get ':id' => 'pages#show'
        get '*section/:id' => 'pages#show'

        get ':id' => 'pages#new'

        put '*section/:id' => 'pages#update'
        put ':id' => 'pages#update'

        delete ':id' => 'pages#destroy'
        delete '*section/:id' => 'pages#destroy'

      end
    end
  end

  #begin хаки для страниц из-за ёбнутейшего роутинга ниже
  #get '/:id' => 'pages#show'
  #end хаки для страниц из-за ёбнутейшего роутинга ниже


  resources :categories, :only => [], :path => '/shop' do
    get 'product/:id' => 'products#show', :as => :product
  end
  resources :categories, :only => [], :path => '/shop/*section' do
    get 'product/:id' => 'products#show', :as => :product
  end


  get '/shop/' => 'categories#index', :as => :shop
  get '/shop/sales' => 'categories#sales', :as => :shop_sales
  get '/shop/:cat_id/product' => 'categories#category', :as => :category
  get '/shop/*section/:cat_id/product' => 'categories#category', :as => :category
  

  resources :pages, :path => "/", :only => [:index, :show]

end

app/models/order.rb
# encoding: utf-8
class Order < ActiveRecord::Base

  attr_accessible :username, :surname, :email, :phone, :address, :comment, :data,
                  :price, :payment, :order_confirm, :confirm

  attr_reader :items
  #
  validates_length_of :username, :in => 2..50, :message => "Имя должно быть длинной не менее 2 и не более 50 символов"
  validates :email, :format => {:with => /[A-Za-z0-9._%+-]+@([A-Za-z0-9-]+\.)+([A-Za-z0-9]{2,4}|museum)/,
                                :message => "Не правильно указан адрес e-mail"}
  validates_length_of :phone, :in => 5..15, :message => "Не указан телефон"
  validates_length_of :address, :in => 5..300, :message => "Не указан адрес"

  #begin объявлеям связь с упражнениями многие ко многим, через соединительную модель motions_programs
  has_many :products_orders
  has_many :products, :through => :products_orders
  #end объявлеям связь с упражнениями многие ко многим, через соединительную модель motions_programs


  def set_price(order_price, product_price)
      self.price = order_price.to_i + product_price
  end

  def re_price(order_price, product_price)
      self.price = 989
  end


end

app/controllers/order_controller.rb
class OrderController < ApplicationController


  def order_add_product

    if session[:order_id]
      @order = Order.find(session[:order_id])
      @order_id = @order.id
    else
      @order = Order.new
      @order.save(:validate => false)
      @order_id = @order.id
      session[:order_id] = @order_id
    end


    @products_order = ProductsOrder.where("product_id = ? AND order_id = ?", params[:id], @order_id).first

    #общая стоимость заказа
    @product = Product.find(params[:id])

    #обновим счётчик для данного продукта
    @product.update_attribute(:hit, @product.hit.to_i + 1)

    if @product.sale.to_i > 0
      @order.set_price(@order.price, @product.price_sale)
    else
      @order.set_price(@order.price, @product.price)
    end

    @order.update_attribute(:confirm, "В процессе")

    if @products_order
      @products_order.update_attributes(:order_id => @order_id, :product_id => params[:id], :size => params[:size], :sum => @products_order.sum + 1)
    else
      @products_order = ProductsOrder.new(:order_id => @order_id, :product_id => params[:id], :size => params[:size], :sum => 1)
      @products_order.save
    end


    @quantity = 0
    for product in @order.products
      @products_orders = ProductsOrder.where("product_id = ? AND order_id = ?", product.id, @order_id).first
      @count = @products_orders.sum
      @quantity = @quantity + @count
    end

    respond_to do |format|
      format.html { redirect_to cart_path(@order) }
      #format.js {}
      format.json { render :json => @order, :status => :created, :location => @order }
    end

  end


  def order_product_count

  end


  def products_order_destroy
    @order = Order.find(params[:id])
    @product = Product.find(params[:product_id])

    #общая стоимость заказа
    @products_order = ProductsOrder.where("product_id = ? AND order_id = ?", params[:product_id], params[:id]).first

    if @product.sale.to_i > 0
      # @order.re_price(@order.price, @product.price_sale.to_i * @products_order.sum)
      @count = @order.price.to_i - @product.price_sale.to_i * @products_order.sum
    else
      # @order.re_price(@order.price, @product.price.to_i * @products_order.sum)
      @count = @order.price.to_i - @product.price.to_i * @products_order.sum
    end
    
    # unless @product.sale
    #   @count = @order.price.to_i - @product.price.to_i * @products_order.sum
    # end
    # if @product.sale
    #   @count = @order.price.to_i - @product.price_sale.to_i * @products_order.sum
    # end
    # 
    @order.update_attribute(:price, @count)

    @order.products.delete(@product)

    respond_to do |format|
      format.html { redirect_to cart_url(@order) }
      format.json { head :no_content }
    end
  end


  def cart
    if session[:order_id]
      @order = Order.find(session[:order_id])
    else
      @order = Order.new
      @order.save(:validate => false)
      session[:order_id] = @order.id
    end
    @order_id = @order.id
    @products = @order.products

    @price = @order.price

    @meta_title = "Корзина"
  end

  def confirm
    @order = Order.find(params[:id])

    @order_id = params[:id]
    @products = @order.products
    @price = @order.price
  end


  def create
    @order = Order.find(params[:id])
    if @order.update_attributes(params[:order])
      session[:order_id] = nil
      redirect_to :action => :show, :id => @order.id
      OrderMailer.order_cofirm(@order).deliver
      OrderMailer.order_cofirm_user(@order).deliver
    else
      render :action => :confirm
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_id = @order.id
    @products = @order.products
    @price = @order.price
  end

end

app/views/order/_form.html.haml
= form_for @order, :url => { :action => :create } do |f|

  .order-form

    %input{:type=>"hidden", :name=>"order[confirm]", :value=> 'Новый'}

    .field
      = f.label :username, "Ваше имя:", :class => "label"
      = f.text_field :username
      - if @order.errors.any?
        .error= @order.errors.messages[:username].join

    .field
      = f.label :email, "Ваш e-mail:", :class => "label"
      = f.text_field :email
      - if @order.errors.any?
        .error= @order.errors.messages[:email].join

    .field
      = f.label :address, "Ваш адрес:", :class => "label"
      = f.text_field :address
      - if @order.errors.any?
        .error= @order.errors.messages[:address].join

    .field
      = f.label :surname, "Ваша фамилия:", :class => "label"
      = f.text_field :surname
      - if @order.errors.any?
        .error= @order.errors.messages[:surname].join

    .field
      = f.label :phone, "Ваш телефон:", :class => "label"
      = f.text_field :phone
      - if @order.errors.any?
        .error= @order.errors.messages[:phone].join
      
      
  .clearfix
    = link_to(cart_path, :class => "btn btn-blue pull-right") do
      %span.btn-in Назад в корзину
    %button.btn.btn_green-buy.pull-left
      %span.btn-in Оформить

app/views/order/cart.haml
.container.blue
  .wrap_offset
    .cart
      %h1 Корзина
      
      -if @products.length != 0
        
        -for product in @products
          -@products_order = ProductsOrder.where("product_id = ? AND order_id = ?", product.id, @order_id).first
          -@count = @products_order.sum
          -@size = @products_order.size
      
          .product_cart
            
            .product_cart-img
              -if product.attachments.find_last
                = image_tag product.attachments.find_last.file_url(:thumb)
              -else
                %img{:src => '/images/nophoto_small.png'}

            .product_cart-desc
              %h2= link_to product.title, "/shop/#{product.category.parent_path}/product/#{product.id}"
              %h3 Описание:
              %div= product.desc

            .product_cart-action
              .product_cart-count
                Количество:
                -#%span.btn.btn-blue.count.js-count-do{:data => {:product => product.id}}
                -#  %span.btn-in -
                %span.product_cart-counter=@count
                -#%span.btn.btn-blue.count.js-count-up{:data => {:product => product.id}}
                  %span.btn-in +

              .product_cart-price
                -unless product.sale 
                  Стоимость:
                  = product.price.to_i * @count
                  руб.
                -if product.sale
                  Стоимость:
                  = product.price_sale.to_i * @count
                  руб.
              = link_to(products_order_destroy_path(@order, product), :method => :delete, :class => "btn btn-red") do
                %span.btn-in Убрать
        
        .cart-price
          Итоговая стоимость:
          = @price.to_i
          руб.

      -else
        %h2 Ваша корзина пуста


-if @products.length != 0
  .container
    .wrap_offset
      .clearfix
        = link_to(:back, :class => "btn btn-blue pull-left") do
          %span.btn-in Назад к товарам
        = link_to(order_confirm_path(@order), :class => "btn btn_green-buy pull-right") do
          %span.btn-in Оформить заказ

app/views/order/confirm.haml
.container.blue
  .wrap_offset
    %h1.inner-page-title Оформление заказа
    = render 'form'

app/views/order/order_add_product.js.erb
//$("<div class='add_cart_success'><div class='add_cart_success-bg'></div><div>Товар добавлен в корзину</div></div>").appendTo("body");

$(".js-cart").html("<%= @quantity %>");


//setTimeout(function(){
//    $('.add_cart_success').remove();
//},700)

app/views/order/show.haml
.container.blue
  .wrap_offset
    %h1 
      Заказ №
      = @order.id
      успешно оформлен
      
    = link_to(shop_path, :class => "btn btn-blue") do
      %span.btn-in Вернуться в магазин