config/routes.rb
Karibuni::Application.routes.draw do

  root :to => 'pages#index'

  #рассылка
  get '/user_start' => 'user#start'
  get '/user_unsubscribe/:id' => 'user#unsubscribe', :as => :unsubscribe
  #рассылка


  #начало роуты для корзины и заказов
  post 'order_add_product' => 'order#order_add_product'
  delete '/products_order_destroy/:id/:product_id' => 'order#products_order_destroy', :as => :products_order_destroy
  #get '/ajax/mini_cart' => 'ajax#mini_cart'
  get 'cart' => 'order#cart', :as => :cart
  get '/order/confirm/:id' => 'order#confirm', :as => :order_confirm
  put 'order/create/:id' => 'order#create'
  get 'order/:id' => 'order#show'
  #конец роуты для корзины и заказов


  resources :feedbacks, :only => [:index, :create]

  #begin ajax
  #get '/ajax/product/:id' => 'ajax#product'
  #end ajax


  get '/admin' => 'admin/dashboard#index'


  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  namespace :admin do
    resources :pages do
      collection do

        post :rebuild

        get ':id/edit' => 'pages#edit'
        get '*section/:id/edit' => 'pages#edit'

        get ':id' => 'pages#show'
        get '*section/:id' => 'pages#show'

        get ':id' => 'pages#new'

        put '*section/:id' => 'pages#update'
        put ':id' => 'pages#update'

        delete ':id' => 'pages#destroy'
        delete '*section/:id' => 'pages#destroy'

      end
    end
  end

  #begin хаки для страниц из-за ёбнутейшего роутинга ниже
  #get '/:id' => 'pages#show'
  #end хаки для страниц из-за ёбнутейшего роутинга ниже


  resources :categories, :only => [], :path => '/shop' do
    get 'product/:id' => 'products#show', :as => :product
  end
  resources :categories, :only => [], :path => '/shop/*section' do
    get 'product/:id' => 'products#show', :as => :product
  end


  get '/shop/' => 'categories#index', :as => :shop
  get '/shop/sales' => 'categories#sales', :as => :shop_sales
  get '/shop/:cat_id/product' => 'categories#category', :as => :category
  get '/shop/*section/:cat_id/product' => 'categories#category', :as => :category
  

  resources :pages, :path => "/", :only => [:index, :show]

end

app/views/shared/_counter.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function () {
            try {
                w.yaCounter21021397 = new Ya.Metrika({id: 21021397,
                    webvisor                            : true,
                    clickmap                            : true,
                    trackLinks                          : true,
                    accurateTrackBounce                 : true,
                    trackHash                           : true});
            } catch (e) {
            }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else {
            f();
        }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript>
  <div><img src="//mc.yandex.ru/watch/21021397" style="position:absolute; left:-9999px;" alt=""/></div>
</noscript>
<!-- /Yandex.Metrika counter -->

app/views/shared/_footer.erb
<footer>

  <div class="clearfix">
    <ul class="menu">
      <%= render_cell :page, :menu %>
    </ul>
    <div class="phone">
      Телефон:
      <b>+7 (985) 489-40-88</b>
    </div>
    <div class="social">
      <span class="title">Мы в социальных сетях:</span>
            <span class="b-share">
                <a class="b-share__handle"><span class="b-share-icon b-share-icon_vkontakte"></span></a>
                <a class="b-share__handle"><span class="b-share-icon b-share-icon_odnoklassniki"></span></a>
                <a class="b-share__handle"><span class="b-share-icon b-share-icon_facebook"></span></a>
                <a class="b-share__handle"><span class="b-share-icon b-share-icon_twitter"></span></a>
            </span>
    </div>
  </div>

  <div class="copyright clearfix">
    © Все права защищены, Karibuni

    <div class="create">
      сделано в
      <%= link_to 'http://rocket-web.ru/', {:target => '_blank'} do %>
          <%= image_tag "rocket-web-blue.png", alt: "Веб студия Rocket-web" %>
      <%- end %>
    </div>

  </div>

</footer>

app/views/shared/_google.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51549888-1', 'karibuni.ru');
  ga('send', 'pageview');

</script>

app/views/shared/_header.erb
<header>

  <a class="logo" href="/"></a>

  <div class="nav">

    <div class="clearfix">
      <ul class="menu main-menu pull-left">
        <%= render_cell :page, :menu %>
      </ul>

      <%= render_cell :cart, :show %>

    </div>

    <hr/>

    <%= render_cell :page, :shop %>
    
  </div>

</header>

app/views/shared/_mini_cart.haml
-if @products.length > 0
  %dl.mini_cart
    %dt КОРЗИНА
    -@products.each do |product|
      %dd
        %div=link_to product.title, [product.category, product]
        %div
          Кол-во:
          -@products_order = ProductsOrder.where("product_id = ? AND order_id = ?", product.id, @order_id).first
          -@count = @products_order.sum
          =@count
        %div
          Цена:
          =product.price.to_i * @count
          руб
    %dd.sum
      Сумма:
      =@price
      руб

    %dd{:style=> "padding:10px 0 0 0"}
      %a{:class=> "button cart-order", :href=> "/cart"} Оформить заказ

app/views/shared/_product.haml
.product_cart
  = form_tag(:controller => "order", :action => "order_add_product", :id => product.id) do

    .product_cart-img
      -if product.attachments.find_last
        = link_to("/shop/#{product.category.parent_path}/product/#{product.id}") do
          = image_tag product.attachments.find_last.file_url(:thumb)
      -else
        = link_to("/shop/#{product.category.parent_path}/product/#{product.id}") do
          %img{:src => '/images/nophoto_small.png'}
      
      -if product.sale
        .product-sale
          .product-sale-bg
          .product-sale-desc
            Скидка
            =product.sale.to_i
            \%
  
    .clearfix
      .pull-left
        %h3.product_cart-title
          = link_to "/shop/#{product.category.parent_path}/product/#{product.id}", :class => 'title'  do
            =product.title
        -unless product.sale
          .product_cart-price
            Цена: 
            = product.price.to_i 
            руб.
        -if product.sale 
          .product_cart-price.old
            Цена: 
            = product.price.to_i 
            руб.
          .product_cart-price
            Цена: 
            = product.price_sale.to_i 
            руб.
      %button.btn.btn_green-add
        %span.btn-in
          %i.icons.icons_cart-white

app/views/shared/_products.erb
<%- for product in @products do %>
    <%= render :partial => 'shared/product', :object => product %>
<%- end %>

app/views/shared/_promo.erb
<div id="promo_block" class="promo_block carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#promo_block" data-slide-to="0" class="active"></li>
    <li data-target="#promo_block" data-slide-to="1"></li>
    <li data-target="#promo_block" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">

    <div class="item active">
      <div class="item-img">
        <img src="/promo/banner1.jpg">
      </div>
      <div class="wrap_offset clearfix">
        <div class="carousel-caption">
          <h2>Летняя одежда и обувь из Африки и Индии</h2>
          <a href="/shop/clothing-and-footwear/product/" class="btn btn_orange"><span class="btn-in">Подробнее</span></a>
        </div>
      </div>
    </div>

    <div class="item blue">
      <div class="item-img">
        <img src="/promo/banner2.jpg">
      </div>
      <div class="wrap_offset clearfix">
        <div class="carousel-caption">
          <h2>Украшения и аксессуары ручной работы</h2>
          <a href="/shop/jewellery-and-accessories/product/" class="btn btn_orange"><span class="btn-in">Подробнее</span></a>
        </div>
      </div>
    </div>

    <div class="item yellow">
      <div class="item-img">
        <img src="/promo/banner3.jpg">
      </div>
      <div class="wrap_offset clearfix">
        <div class="carousel-caption">
          <h2>Сувениры и домашний текстиль</h2>
          <a href="/shop/souvenirs-and-decorative-items/product/" class="btn btn_green"><span class="btn-in">Подробнее</span></a>
        </div>
      </div>
    </div>

  </div>

</div>

app/views/shared/_promo_products.haml
.container
  .wrap_offset
    .products_sales

      - @products_hit.each do |product|
        .product_cart.hit
          = form_tag(:controller => "order", :action => "order_add_product", :id => product.id) do

            .product_cart-img
              -if product.attachments.find_last
                = link_to("/shop/#{product.category.parent_path}/product/#{product.id}") do
                  = image_tag product.attachments.find_last.file_url(:promo)
              -else
                = link_to("/shop/#{product.category.parent_path}/product/#{product.id}") do
                  %img{:src => '/images/nophoto_small.png'}

            .product_cart-desc
              %h3.product_cart-title
                = link_to "/shop/#{product.category.parent_path}/product/#{product.id}" do
                  =product.title
              .product_cart-price
                Цена: 
                = product.price.to_i 
                руб.

            %button.btn.btn_green-add
              %span.btn-in
                %i.icons.icons_cart-white
                Заказать


      -#= debug @products_sale
      - @products_sale.each do |product|
        .product_cart.sale
          = link_to shop_sales_path do
            .product_cart-img
              -if product.attachments.find_last
                = image_tag product.attachments.find_last.file_url(:promo)
              -else
                %img{:src => '/images/nophoto_small.png'}
    
            .product_cart-desc
              %h3.product_cart-title
                Скидки до
                =product.sale.to_i 
                \%
  
          = link_to shop_sales_path, :class => "btn btn_red-add" do
            %span.btn-in
              Все скидки                                

app/views/shared/_share.erb
<h3>Поделиться:</h3>
<script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
<div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="none" data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki"></div> 